/**
 * Cloudflare Email Service types are generated by Wrangler into each Worker
 * project's `cloudflare-env.d.ts` file. This reusable package cannot import
 * those project-specific globals, so it defines the structural types it needs
 * to call the EMAIL binding instead.
 */

export type CloudflareEmailAddress = {
  email: string
  name: string
}

export type CloudflareEmailAddressValue = string | CloudflareEmailAddress
export type CloudflareEmailRecipients = CloudflareEmailAddressValue | CloudflareEmailAddressValue[]

export type CloudflareEmailDestinations = {
  bcc?: CloudflareEmailRecipients
  cc?: CloudflareEmailRecipients
  to?: CloudflareEmailRecipients
} & (
  | { to: CloudflareEmailRecipients }
  | { cc: CloudflareEmailRecipients }
  | { bcc: CloudflareEmailRecipients }
)

export type CloudflareEmailMessage = CloudflareEmailDestinations & {
  from: CloudflareEmailAddressValue
  headers?: Record<string, string>
  html?: string
  replyTo?: CloudflareEmailAddressValue
  subject: string
  text?: string
}

export interface EmailBinding<TResponse = unknown> {
  send(message: CloudflareEmailMessage): Promise<TResponse>
}

export type EmailAdapterArgs<TResponse = unknown> = {
  defaultFromAddress: string
  defaultFromName: string
  binding: EmailBinding<TResponse>
}
