/**
 * Copied from the Cloudflare runtime types generated by Wrangler. This package
 * cannot import the project-specific globals from `cloudflare-env.d.ts`, so it
 * exports the same structural types for the Email Service binding.
 */

/**
 * The returned data after sending an email
 */
export interface EmailSendResult {
  /**
   * The Email Message ID
   */
  messageId: string
}

/**
 * An email message that can be sent from a Worker.
 */
export interface EmailMessage {
  /**
   * Envelope From attribute of the email message.
   */
  readonly from: string
  /**
   * Envelope To attribute of the email message.
   */
  readonly to: string
}

/** A file attachment for an email message */
export type EmailAttachment =
  | {
      disposition: 'inline'
      contentId: string
      filename: string
      type: string
      content: string | ArrayBuffer | ArrayBufferView
    }
  | {
      disposition: 'attachment'
      contentId?: undefined
      filename: string
      type: string
      content: string | ArrayBuffer | ArrayBufferView
    }

/** An Email Address */
export interface EmailAddress {
  name: string
  email: string
}

/**
 * Recipient fields for `SendEmail.send()`. At least one of `to`, `cc`, or
 * `bcc` must be provided.
 */
export type EmailDestinations = {
  to?: string | EmailAddress | (string | EmailAddress)[]
  cc?: string | EmailAddress | (string | EmailAddress)[]
  bcc?: string | EmailAddress | (string | EmailAddress)[]
} & (
  | {
      to: string | EmailAddress | (string | EmailAddress)[]
    }
  | {
      cc: string | EmailAddress | (string | EmailAddress)[]
    }
  | {
      bcc: string | EmailAddress | (string | EmailAddress)[]
    }
)

/**
 * Fields shared by all composed emails (no recipients). Used directly by
 * `ForwardableEmailMessage.reply()`, which always replies to the original
 * sender, and extended by `EmailMessageBuilder` for `SendEmail.send()`.
 */
export interface EmailReplyMessageBuilder {
  from: string | EmailAddress
  subject: string
  replyTo?: string | EmailAddress
  headers?: Record<string, string>
  text?: string
  html?: string
  attachments?: EmailAttachment[]
}

/**
 * Fields for composing an email without constructing raw MIME, for
 * `SendEmail.send()`. Requires at least one of `to`, `cc`, or `bcc`.
 */
export type EmailMessageBuilder = EmailReplyMessageBuilder & EmailDestinations

/**
 * A binding that allows a Worker to send email messages.
 */
export interface SendEmail {
  send(message: EmailMessage): Promise<EmailSendResult>
  send(builder: EmailMessageBuilder): Promise<EmailSendResult>
}

export type EmailAdapterArgs = {
  defaultFromAddress: string
  defaultFromName: string
  binding: SendEmail
}
